POST http://localhost:3003/user HTTP/1.1
content-type: application/json

{  
"user": "ash@evildead.com",
    "password": "ashpasswd",
    "nickname": "ashwilliams"
}
###
POST http://localhost:3003/user/login HTTP/1.1
content-type: application/json

{  
    "user": "ash@evildead.com",
    "password": "ashpasswd"
}
###
PUT http://localhost:3003/user/62467ba7fe36c46d0b0d4437  HTTP/1.1
content-type: application/json

{ "user":{  
    "name": "Ash Williams",
    "img": "",
    "birth_date": "07/12/1954",
    "social": {
        "instagram": "@evildead",
        "facebook": "evildead",
        "twitch": "evildead_twitch",
        "youtube": "evildead_youtube"
    },
    "badges": ["demon killer"],
    "score": 92,
    "ranking": 0,
    "tournament": [{ 
    "tornament": "Magic Palper", 
    "totalScore": 123, 
    "results": 55
    }],
    "wallet": ""
}
}
###
PUT http://localhost:3003/user/624621994e2d453bb3683654 HTTP/1.1
content-type: application/json

{"user":{  
    "name": "Jason Vorhees"}
}
###
DELETE http://localhost:3003/user/62467ba7fe36c46d0b0d4437 HTTP/1.1
content-type: application/json

###