POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{  
"user": "ash@evildead.com",
    "password": "ashpasswd",
    "nickname": "ashwilliams"
}
###
POST http://localhost:3000/user/login HTTP/1.1
content-type: application/json

{  
    "user": "ash@evildead.com",
    "password": "ashpasswd"
}
###
PUT http://localhost:3000/user/60feeb3c479d6b6067e7f233  HTTP/1.1
content-type: application/json

{ "user":{  
    "name": "Ash Williams",
    "img": "",
    "birth_date": "07/12/1954",
    "social": {
        "instagram": "@evildead",
        "facebook": "evildead",
        "twitch": "evildead_twitch",
        "youtube": "evildead_youtube"
    },
    "badges": ["demon killer"],
    "stakers": [],
    "score": { "w": 92, "l": 99, "d": 11 },
    "ranking": [],
    "tournament": [{ 
    "tornament": "Magic Palper", 
    "totalScore": 123, 
    "results": 55
    }],
    "evo": [],
    "wallet": ""
}
}
###
PUT http://localhost:3000/user/60fc32301a68ef39e7f7dbd4 HTTP/1.1
content-type: application/json

{"user":{  
    "name": "Jason Vorhees"}
}
###